---
- name: Check if file exists and set its content to only our content variable
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    content: Hello world you
  tasks:
    - name: Write content to file
      lineinfile:
        path: ./output.txt
        regexp: Hello|World
        line: "{{ content }}"
        state: present
        create: yes
